### ISSUE TITLE
Program a log-loss function for the kaggle competition

### ISSUE THREAD

**Issue by Wangbarros** [Wangbarros/Kaggle_Quora#2]

**Comment by denotepython** [comment]
hello ,thanks for your data , can you share the test data too, I have failed serveral times when I try to download from the kaggle website

**Comment by Wangbarros** [comment]
Sorry, I am having trouble in uploading the test data to github due to its size =/

**Comment by denotepython** [comment]
thank you anyway,I will try other method.
